# Generated by Django 4.2.4 on 2023-08-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director_tecnico',
            options={'verbose_name': 'Director Tecnico', 'verbose_name_plural': 'Directores Tecnicos'},
        ),
        migrations.AlterModelOptions(
            name='estadio',
            options={'verbose_name': 'Estadio', 'verbose_name_plural': 'Estadios'},
        ),
        migrations.AlterModelOptions(
            name='jugadores',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='socios',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterModelOptions(
            name='tribunas',
            options={'verbose_name': 'Tribuna', 'verbose_name_plural': 'Tribunas'},
        ),
        migrations.AlterField(
            model_name='estadio',
            name='historia',
            field=models.CharField(max_length=100000000000),
        ),
    ]
