# Generated by Django 4.2.4 on 2023-09-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_director_tecnico_options_alter_estadio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_tecnico',
            name='numero',
            field=models.CharField(max_length=30),
        ),
    ]
