# Generated by Django 4.2.4 on 2023-09-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quien_Soy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quien_soy', models.CharField(max_length=100000)),
            ],
            options={
                'verbose_name': 'Quien Soy',
                'verbose_name_plural': 'Quienes Somos',
            },
        ),
    ]
