# Generated by Django 4.2.4 on 2023-09-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_cancion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancion',
            options={'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
    ]
